server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springSequrity
    username: root
    password: *******
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


  application:
      security:
        jwt:
          secret-key: ddacb9b9635f03dba48898b317962b2b409a1527e54e7ed4a27425604b161a9f
          expiration: 86400000 #1day
#         expiration: 60000 1 min
          refresh-token:
            expiration: 604800000 #7 days
            #expiration: 604800000 5min









